// Editorial layer — early 2026 snapshot. Edit freely; you are the commissioner.
export const TITLES: Record<string, string> = {
  "muhammad-ali": "3× Lineal Heavyweight Champion (1964–67, 1974–78, 1978–79)",
  "sugar-ray-robinson": "Welterweight Champion (1946–51) · 5× Middleweight Champion",
  "joe-louis": "Heavyweight Champion (1937–1949), 25 defenses",
  "rocky-marciano": "Heavyweight Champion (1952–1956), retired undefeated",
  "jack-dempsey": "Heavyweight Champion (1919–1926)",
  "joe-frazier": "Undisputed Heavyweight Champion (1970–1973)",
  "george-foreman": "2× Heavyweight Champion (1973–74, 1994–95)",
  "larry-holmes": "WBC/IBF Heavyweight Champion (1978–1985), 20 defenses",
  "mike-tyson": "Undisputed Heavyweight Champion (1987–1990)",
  "evander-holyfield": "Undisputed Cruiserweight & 4× Heavyweight Champion",
  "lennox-lewis": "Undisputed Heavyweight Champion (1999–2000)",
  "marvin-hagler": "Undisputed Middleweight Champion (1980–1987)",
  "sugar-ray-leonard": "World titles in 5 divisions (welterweight to light heavy)",
  "thomas-hearns": "World titles in 5 divisions, first to win 4",
  "roberto-duran": "World titles in 4 divisions across 3 decades",
  "julio-cesar-chavez": "World titles in 3 divisions · 87–0 start",
  "pernell-whitaker": "Undisputed Lightweight Champion · titles in 4 divisions",
  "oscar-de-la-hoya": "World titles in 6 divisions",
  "felix-trinidad": "World titles in 3 divisions",
  "bernard-hopkins": "Undisputed Middleweight Champion, 20 defenses · oldest champ ever",
  "roy-jones-jr": "World titles middleweight to heavyweight",
  "floyd-mayweather": "World titles in 5 divisions, 50–0",
  "manny-pacquiao": "Only 8-division world champion in history",
  "juan-manuel-marquez": "World titles in 4 divisions",
  "erik-morales": "First Mexican-born 4-division champion",
  "marco-antonio-barrera": "World titles in 3 divisions",
  "miguel-cotto": "First Puerto Rican 4-division champion",
  "wladimir-klitschko": "2× Unified Heavyweight Champion (2000–03, 2006–15)",
  "vitali-klitschko": "2× Heavyweight Champion, never knocked down",
  "canelo-alvarez": "Former Undisputed Super Middleweight Champion · 4-division champ",
  "gennady-golovkin": "Unified Middleweight Champion, 21 defenses",
  "tyson-fury": "Lineal & WBC Heavyweight Champion (2015, 2020–2024)",
  "deontay-wilder": "WBC Heavyweight Champion (2015–2020)",
  "anthony-joshua": "2× Unified Heavyweight Champion",
  "oleksandr-usyk": "Undisputed Cruiserweight & Undisputed Heavyweight Champion",
  "terence-crawford": "Undisputed at 140, 147 & 168 — first 3× undisputed champ",
  "errol-spence-jr": "Unified Welterweight Champion (2017–2023)",
  "naoya-inoue": "Undisputed Bantamweight & Super Bantamweight Champion",
  "gervonta-davis": "World titles in 3 divisions",
  "devin-haney": "Undisputed Lightweight Champion (2022–23)",
  "shakur-stevenson": "World titles in 3 divisions",
  "david-benavidez": "WBC Light Heavyweight Champion · 2× super middle champ",
  "dmitry-bivol": "Undisputed Light Heavyweight Champion (2024–25)",
  "artur-beterbiev": "Undisputed Light Heavyweight Champion (2024–25)",
  "royce-gracie": "UFC 1, 2 & 4 tournament champion",
  "fedor-emelianenko": "PRIDE Heavyweight Champion (2003–2007)",
  "chuck-liddell": "UFC Light Heavyweight Champion (2005–2007)",
  "randy-couture": "3× UFC Heavyweight & 2× Light Heavyweight Champion",
  "wanderlei-silva": "PRIDE Middleweight Champion (2001–2007)",
  "mirko-cro-cop": "PRIDE 2006 Open-Weight Grand Prix Champion",
  "bj-penn": "UFC Welterweight & Lightweight Champion",
  "anderson-silva": "UFC Middleweight Champion (2006–2013), longest title reign",
  "georges-st-pierre": "UFC Welterweight & Middleweight Champion",
  "jon-jones": "UFC Light Heavyweight & Heavyweight Champion",
  "khabib-nurmagomedov": "UFC Lightweight Champion (2018–2020), 29–0",
  "daniel-cormier": "UFC Heavyweight & Light Heavyweight Champion (simultaneous)",
  "stipe-miocic": "2× UFC Heavyweight Champion, most HW title defenses",
  "demetrious-johnson": "UFC Flyweight Champion (2012–2018), 11 defenses · ONE Champion",
  "jose-aldo": "UFC/WEC Featherweight Champion (2009–2015)",
  "dominick-cruz": "2× UFC Bantamweight Champion",
  "conor-mcgregor": "UFC Featherweight & Lightweight Champion — first double champ",
  "amanda-nunes": "UFC Bantamweight & Featherweight Champion (simultaneous)",
  "ronda-rousey": "UFC Bantamweight Champion (2012–2015)",
  "valentina-shevchenko": "2× UFC Flyweight Champion",
  "joanna-jedrzejczyk": "UFC Strawweight Champion (2015–2017), 5 defenses",
  "zhang-weili": "2× UFC Strawweight Champion",
  "israel-adesanya": "2× UFC Middleweight Champion",
  "alex-pereira": "UFC Middleweight & Light Heavyweight Champion",
  "alexander-volkanovski": "2× UFC Featherweight Champion",
  "islam-makhachev": "UFC Lightweight & Welterweight Champion",
  "kamaru-usman": "UFC Welterweight Champion (2019–2022), 5 defenses",
  "leon-edwards": "UFC Welterweight Champion (2022–2024)",
  "max-holloway": "UFC Featherweight Champion · BMF Champion",
  "charles-oliveira": "UFC Lightweight Champion (2021–2022)",
  "sean-omalley": "UFC Bantamweight Champion (2023–2024)",
  "ilia-topuria": "UFC Featherweight & Lightweight Champion",
  "tom-aspinall": "UFC Heavyweight Champion",
  "michael-bisping": "UFC Middleweight Champion (2016–2017)",
  "chael-sonnen": "Undefeated, Undisputed, The Bad Guy",
  "kazushi-sakuraba": "UFC Japan Heavyweight Tournament winner · PRIDE legend",
  "shogun-rua": "PRIDE 2005 Grand Prix Champion · UFC Light Heavyweight Champion",
  "quinton-rampage-jackson": "UFC Light Heavyweight Champion (2007)",
  "antonio-rodrigo-nogueira": "PRIDE & Interim UFC Heavyweight Champion",
  "dan-henderson": "PRIDE Welterweight & Middleweight Champion (simultaneous)",
  "tito-ortiz": "UFC Light Heavyweight Champion (2000–2003), 5 defenses",
  "matt-hughes": "2× UFC Welterweight Champion, 7 defenses",
  "lyoto-machida": "UFC Light Heavyweight Champion (2009–2010)",
  "rashad-evans": "UFC Light Heavyweight Champion (2008)",
  "cain-velasquez": "2× UFC Heavyweight Champion",
  "junior-dos-santos": "UFC Heavyweight Champion (2011–2012)",
  "fabricio-werdum": "UFC Heavyweight Champion (2015–2016)",
  "frankie-edgar": "UFC Lightweight Champion (2010–2012)",
  "holly-holm": "UFC Bantamweight Champion · 3-division boxing world champion",
  "cris-cyborg": "Champion in UFC, Strikeforce, Invicta, Bellator & PFL",
  "henry-cejudo": "UFC Flyweight & Bantamweight Champion · Olympic gold",
  "aljamain-sterling": "UFC Bantamweight Champion (2021–2023)",
  "merab-dvalishvili": "UFC Bantamweight Champion",
  "robert-whittaker": "UFC Middleweight Champion (2017–2019)",
  "jiri-prochazka": "UFC Light Heavyweight Champion (2022)",
  "sean-strickland": "2× UFC Middleweight Champion (2023–24, 2026–present)",
  "dricus-du-plessis": "UFC Middleweight Champion",
  "alexandre-pantoja": "UFC Flyweight Champion",
  "belal-muhammad": "UFC Welterweight Champion (2024–2025)",
  "justin-gaethje": "UFC Lightweight Champion · BMF Champion",
  "mark-coleman": "UFC Heavyweight Champion · PRIDE 2000 GP Champion",
  "josh-barnett": "UFC Heavyweight Champion (2002)",
  "ken-shamrock": "UFC Superfight Champion · Hall of Famer",
  "bas-rutten": "UFC Heavyweight Champion · 3× King of Pancrase",
  "takanori-gomi": "PRIDE Lightweight Champion",
  "petr-yan": "2× UFC Bantamweight Champion",
  "joshua-van": "UFC Flyweight Champion",
  "kayla-harrison": "UFC Women's Bantamweight Champion · 2× Olympic gold",
  "mackenzie-dern": "UFC Women's Strawweight Champion (2025–26)",
  "jack-della-maddalena": "UFC Welterweight Champion (2025)",
  "khamzat-chimaev": "UFC Middleweight Champion (2025–2026)",
  "carlos-ulberg": "UFC Light Heavyweight Champion",
  "jamahal-hill": "UFC Light Heavyweight Champion (2023)",
  "glover-teixeira": "UFC Light Heavyweight Champion (2021–2022)",
  "francis-ngannou": "UFC Heavyweight Champion (2021–2023)",
  "brock-lesnar": "UFC Heavyweight Champion (2008–2010)",
  "alistair-overeem": "Strikeforce, DREAM & K-1 GP Champion",
  "andrei-arlovski": "UFC Heavyweight Champion (2005–2006)",
  "frank-mir": "2× UFC Heavyweight Champion",
  "tim-sylvia": "2× UFC Heavyweight Champion",
  "mark-hunt": "K-1 World Grand Prix Champion (2001)",
  "ryan-bader": "Bellator Heavyweight & Light Heavyweight Champion",
  "eddie-alvarez": "UFC & Bellator Lightweight Champion",
  "tony-ferguson": "UFC Interim Lightweight Champion · 12-fight win streak",
  "anthony-pettis": "UFC & WEC Lightweight Champion",
  "luke-rockhold": "UFC & Strikeforce Middleweight Champion",
  "forrest-griffin": "UFC Light Heavyweight Champion · TUF 1 winner",
  "benson-henderson": "UFC & WEC Lightweight Champion",
  "dan-severn": "UFC Superfight Champion · Hall of Famer",
  "robbie-lawler": "UFC Welterweight Champion (2014–2016)",
  "tyron-woodley": "UFC Welterweight Champion (2016–2019)",
  "johny-hendricks": "UFC Welterweight Champion (2014)",
  "rich-franklin": "UFC Middleweight Champion (2005–2006)",
  "matt-serra": "UFC Welterweight Champion (2007)",
  "carlos-condit": "WEC Welterweight & Interim UFC Champion",
  "jorge-masvidal": "First BMF Champion",
  "chris-weidman": "UFC Middleweight Champion (2013–2015)",
  "ben-askren": "Bellator & ONE Welterweight Champion, retired undefeated in title runs",
};

// Who currently holds a belt (early 2026 snapshot — EDIT as belts change)
export const REIGNING = new Set<string>([
  // Boxing
  "oleksandr-usyk", "terence-crawford", "naoya-inoue", "david-benavidez",
  // UFC — July 2026
  "tom-aspinall",        // HW
  "carlos-ulberg",       // LHW
  "sean-strickland",     // MW
  "islam-makhachev",     // WW
  "justin-gaethje",      // LW
  "alexander-volkanovski", // FW
  "petr-yan",            // BW
  "joshua-van",          // FLW
  "kayla-harrison",      // W-BW
  "valentina-shevchenko",// W-FLW
  // W-SW vacant
]);

// Records for actives missing one (editorial, may lag reality)
export const RECORDS: Record<string, string> = {
  "jon-jones": "28–1 (1 NC)",
  "islam-makhachev": "27–1",
  "alexander-volkanovski": "27–4",
  "ilia-topuria": "17–0",
  "alex-pereira": "13–3",
  "max-holloway": "26–8",
  "charles-oliveira": "35–11",
  "dustin-poirier": "30–10",
  "justin-gaethje": "26–5",
  "kamaru-usman": "20–4",
  "leon-edwards": "22–5",
  "israel-adesanya": "24–5",
  "sean-omalley": "18–3",
  "tom-aspinall": "15–3",
  "canelo-alvarez": "62–3–2",
  "tyson-fury": "34–2–1",
  "anthony-joshua": "28–4",
  "oleksandr-usyk": "24–0",
  "terence-crawford": "42–0",
  "naoya-inoue": "30–0",
};

// Alias search: alternate spellings/nicknames → slug
export const ALIASES: Record<string, string> = {
  "connor mcgregor": "conor-mcgregor",
  "the notorious": "conor-mcgregor",
  "gsp": "georges-st-pierre",
  "bones": "jon-jones",
  "the eagle": "khabib-nurmagomedov",
  "iron mike": "mike-tyson",
  "money mayweather": "floyd-mayweather",
  "pacman": "manny-pacquiao",
  "triple g": "gennady-golovkin",
  "ggg": "gennady-golovkin",
  "poatan": "alex-pereira",
  "suga": "sean-omalley",
  "tank davis": "gervonta-davis",
};
export const OPPONENT_ALIASES: Record<string, string> = {
  "quinton jackson": "quinton-rampage-jackson",
  "rampage jackson": "quinton-rampage-jackson",
  "mauricio rua": "shogun-rua",
  "maurício rua": "shogun-rua",
  "shogun rua": "shogun-rua",
  "antonio rodrigo nogueira": "antonio-rodrigo-nogueira",
  "minotauro nogueira": "antonio-rodrigo-nogueira",
  "antonio rogerio nogueira": "antonio-rogerio-nogueira",
  "mirko filipovic": "mirko-cro-cop",
  "mirko filipović": "mirko-cro-cop",
  "b.j. penn": "bj-penn",
};